version: "3"
services:
  backend:
    container_name: "node_backend"
    build: ./backend/
    depends_on:
      - db
    ports:
      - "3001:3001"
    command: npm run dev
    volumes:
      - ${PWD}/backend:/usr/src/app

  db:
    image: "postgres:12"
    container_name: "postgres"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/postgres/data/:/var/lib/postgresql/data

  frontend:
    container_name: "react_frontend"
    build: ./frontend/
    depends_on:
      - backend
    ports:
      - "3002:3000"
    stdin_open: true
    command: npm start
    volumes:
      - ${PWD}/frontend:/usr/src/app
